### ISSUE TITLE
Controller Design Review

### ISSUE THREAD

**Issue by wlan0** [kubernetes-sigs/container-object-storage-interface-api#19]
https://github.com/kubernetes-sigs/container-object-storage-interface-api/blob/master/controller/controller.go
- Review the controller design since it was custom built and doesn’t use kube-builder api.  We wanted something much simpler and easier to use
- Ensure that there are no deadlocks/race conditions
- Ensure that retries, updates, additions and deletions work as expected of a standard kubernetes controller.

**Comment by BlaineEXE** [comment]
I am curious why the project opted not to use [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). Rook uses the controller-runtime directly, and I find it to be quite simple and usable. kube-builder and Operator SDK both build on top of controller-runtime.
