### ISSUE TITLE
Found a broken link at /docs/index.md

### ISSUE THREAD

**Issue by AdityaC45** [kubernetes-sigs/container-object-storage-interface-api#45]
The link is present under the 
- Links section:
         - user guide
         - How to write a COSI driver
         - How to make your application COSI-compatible
- Advanced section:
         - Protocols
         - Architecture
         - Internals
- Other:
         - Weekly Meetings

**Comment by AdityaC45** [comment]
I think the document is not yet created, I can work on this issue but will need help on the content that needs to be added to that document

**Comment by guymguym** [comment]
I think the docs moved here - https://container-object-storage-interface.github.io/
Still worth updating the main README.md because it's just bad that those links are broken...
CC @wlan0

**Comment by guymguym** [comment]
The docs source project:
- https://github.com/container-object-storage-interface/container-object-storage-interface.github.io

**Comment by AdityaC45** [comment]
Hi , I went through that link but still there are no contents added to some of the docs so if we are going to update the documentation in the link shared then it will be good otherwise we again have to change the link

**Comment by tparikh** [comment]
Thanks for reporting this issue @AdityaC45. I will take a look into this and update the docs and links.

/assign @tparikh

**Comment by AdityaC45** [comment]
If you need any help, I will be glad to help you @tparikh

**Comment by tparikh** [comment]
@AdityaC45 I have raised PR to fix the broken link to documentation. Team is working on populating the empty pages on the documentation site.

**Comment by AdityaC45** [comment]
Ohkk thanks👍
